export default [
    {   id:1,
        title:"Mount Fuji",
        location:'Japan',
        googleMapsUrl:'https://goo.gl/maps/HdA7KPWdVMkDDsFx8',
        description:'Iconic snow-capped peak & volcano, the highest in Japan & the 7th highest island peak on earth.',
        startDate:'12 Jan,2024',
        endDate:"24 Jan, 2024",
        imageUrl:"https://images.unsplash.com/photo-1578271887552-5ac3a72752bc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
    },
    {   id:2,
        title:"Meteora",
        location:'Greece',
        googleMapsUrl:'https://goo.gl/maps/FkrvVW5DjKekLuYWA',
        description:'6 Eastern Orthodox monasteries listed as a World Heritage site, built on top of rock pillars.',
        startDate:'12 April,2023',
        endDate:"24 April, 2023",
        imageUrl:"https://images.unsplash.com/photo-1629295250695-cde582b4c1f6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80"
    },
    {   id:3,
        title:"Giza",
        location:'Egypt',
        googleMapsUrl:'https://goo.gl/maps/CgmcekFDnZo9uddH7',
        description:'Giza is an Egyptian city on the west bank of the Nile, near Cairo. The Giza Plateau is home to iconic Egyptian monuments.',
        startDate:'1 May,2023',
        endDate:"14 May, 2023",
        imageUrl:"https://images.unsplash.com/photo-1669301038557-f84309ac1269?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
    },
       {   id:4,
        title:"Pompei",
        location:'Italy',
        googleMapsUrl:'https://goo.gl/maps/zAyTXTXKZzeFvPwq8',
        description:'Pompei is a city in southern Italy’s Campania region overlooked by the active volcano at Vesuvius. It’s known for its ancient city, Pompeii, which was buried by the 79 A.D. eruption of Mount Vesuvius. ',
        startDate:'1 May,2023',
        endDate:"14 May, 2023",
        imageUrl:" https://images.unsplash.com/photo-1561717690-81fbd538866b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
    },
       {   id:5,
        title:"Giza",
        location:'India',
        googleMapsUrl:'https://goo.gl/maps/HmgGjjpNRNLUbYHS7',
        description:'17th-century, Mughal-style, marble mausoleum with minarets, a mosque & famously symmetrical gardens.',
        startDate:'1 May,2023',
        endDate:"14 May, 2023",
        imageUrl:"https://www.tajmahal.gov.in/images/banners/1.jpg"
    },
       {   id:6,
        title:"Cappadocia",
        location:'Türkiye',
        googleMapsUrl:'https://goo.gl/maps/dinK5K6XPuiALzRZA',
        description:'Cappadocia, a semi-arid region in central Turkey, is known for its distinctive “fairy chimneys,” tall, cone-shaped rock formations clustered in Monks Valley, Göreme and elsewhere. ',
        startDate:'1 May,2023',
        endDate:"14 May, 2023",
        imageUrl:"https://images.unsplash.com/photo-1605213605677-861baf60c228?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80"
    }
]